defmodule ApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :api

  # Sessão no cookie, CIFRADA e assinada (AEAD). Sem o :encryption_salt o cookie era só
  # assinado: íntegro, mas legível por base64 puro (a chave `user_token` e o JWT inteiro
  # à mostra para quem tivesse o valor). Os salts não são segredo — só derivam chaves
  # distintas do secret_key_base; trocá-los derruba as sessões ativas (doc 14 §2).
  @session_options [
    store: :cookie,
    key: "_api_key",
    signing_salt: "QExDiC7H",
    encryption_salt: "319wcRWM",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :api,
    gzip: not code_reloading?,
    only: ApiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, AshJsonApi.Plug.Parser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ApiWeb.Router
end
