defmodule ApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :api

  # Sessão no cookie, CIFRADA e assinada (AEAD). Sem o :encryption_salt o cookie era só
  # assinado: íntegro, mas legível por base64 puro (a chave `user_token` e o JWT inteiro
  # à mostra para quem tivesse o valor). Os salts não são segredo — só derivam chaves
  # distintas do secret_key_base; trocá-los derruba as sessões ativas (doc 14 §2).
  @session_options [
    store: :cookie,
    key: "_api_key",
    signing_salt: "QExDiC7H",
    encryption_salt: "319wcRWM",
    same_site: "Lax"
  ]

  # O tempo real da agenda (ADR-004, Entrega 3). Autenticação pelo token efêmero, não pela
  # sessão — ver `ApiWeb.UserSocket`. Sem `longpoll`: o cliente é o pacote `phoenix` no
  # browser, e o fallback só acrescentaria superfície.
  #
  # `auth_token: true` (S2, Onda 5) faz o token chegar pelo subprotocolo `Sec-WebSocket-Protocol`
  # em vez da query string, onde vazava para log de proxy. É o mesmo interruptor dos dois lados:
  # sem ele aqui, o `authToken:` do cliente é ignorado e ninguém conecta.
  #
  # **A opção é do SOCKET, não do `websocket:`.** Escrita como `websocket: [auth_token: true]` ela
  # é silenciosamente anulada: o `put_auth_token/2` do Phoenix faz
  # `Keyword.put(websocket, :auth_token, opts[:auth_token])`, e com a chave ausente aqui fora o
  # `opts[:auth_token]` é `nil` — sobrescrevendo o `true` de dentro. O sintoma é 403 no handshake
  # com tudo verde no `mix test`, porque o `Phoenix.ChannelTest` injeta `connect_info` direto e
  # nunca passa pelo transporte. Achado ao vivo, no browser.
  socket "/socket", ApiWeb.UserSocket, auth_token: true, websocket: true, longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :api,
    gzip: not code_reloading?,
    only: ApiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
  end

  plug Plug.RequestId
  # Logo depois do `RequestId`, e pela mesma razão: carimbar o identificador no Logger antes de
  # qualquer plug que possa logar. O span já existe aqui — quem o abriu foi o
  # `opentelemetry_bandit`, no evento de início da requisição, antes de o Bandit chamar o plug.
  plug ApiWeb.Plugs.TraceMetadata
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, AshJsonApi.Plug.Parser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Doc 52 §10.2: o webhook do Resend assina os **bytes** do corpo. Depois da decodificação,
    # reserializar o mapa produz bytes diferentes e a assinatura nunca fecha. Este body reader
    # retém o corpo cru — só nas rotas que precisam dele (ver o módulo).
    body_reader: {ApiWeb.Plugs.CacheRawBody, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ApiWeb.Router
end
