defmodule Api.Repo.Migrations.InvariantesDeDominioNoBanco do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  ## Notas de revisão (doc 92, P2-7 e P2-8)

  **Os quatro `CHECK` são invariantes que já existiam — no Ash.** Cada um tem `validate`
  correspondente no recurso; o que faltava era o banco também saber, para que migration,
  `Ash.Seed`, script e `psql` não passassem por baixo. O de `package_schedules` é o mais gritante:
  o comentário do atributo `dows` afirmava que a constraint existia.

  **Eram cinco.** O quinto — `appointment_types`, "capacidade sse grupo" — foi **recusado**: ele
  quebra o fallback defensivo de `Clinic.cap_turma_padrao`, que existe justamente para a linha
  escrita fora das ações. Ver a nota no `postgres do` de `Api.Directory.AppointmentType`.

  **Sem `CONCURRENTLY` e sem `NOT VALID`, de propósito.** `ADD CONSTRAINT` valida a tabela inteira
  sob `AccessExclusiveLock`; medido no dev, a maior das quatro é `clinic_hours` com 2.891 linhas
  (728 kB) — validação instantânea. O padrão `ADD CONSTRAINT … NOT VALID` + `VALIDATE CONSTRAINT`
  em duas transações é o certo para tabela grande, e é o que este comentário existe para lembrar
  caso alguma delas cresça.

  **Antes de aplicar em produção**, confira que os dados passam — se não passarem, a migration
  aborta (falha segura, nada é corrompido), mas o deploy para:

      SELECT 'package_schedules' t, count(*) FROM package_schedules WHERE NOT (dows <@ ARRAY[0,1,2,3,4,5,6]::bigint[])
      UNION ALL SELECT 'clinic_hours', count(*) FROM clinic_hours WHERE dow NOT BETWEEN 0 AND 6
      UNION ALL SELECT 'professional_hours', count(*) FROM professional_hours WHERE dow NOT BETWEEN 0 AND 6
      UNION ALL SELECT 'availability_rules', count(*) FROM availability_rules
        WHERE NOT ((tipo = 'semana' AND coalesce(array_length(dows,1),0) > 0) OR (tipo = 'data' AND data IS NOT NULL))
      UNION ALL SELECT 'messages dup', count(*) FROM (
        SELECT provider_message_id FROM messages WHERE provider_message_id IS NOT NULL
         GROUP BY 1 HAVING count(*) > 1) d;

  No dev, em 2026-08-04, os cinco deram **0**.
  """

  use Ecto.Migration

  def up do
    drop_if_exists(index(:messages, [:provider_message_id], name: "messages_provider_id_index"))

    create index(:messages, [:provider_message_id],
             name: "messages_provider_id_index",
             unique: true,
             where: "provider_message_id IS NOT NULL"
           )

    create constraint(:availability_rules, :availability_rules_forma,
             check: """
               (tipo = 'semana' AND coalesce(array_length(dows, 1), 0) > 0) OR (tipo = 'data' AND data IS NOT NULL)
             """
           )

    create constraint(:clinic_hours, :clinic_hours_dow_range,
             check: """
               dow BETWEEN 0 AND 6
             """
           )

    create constraint(:package_schedules, :package_schedules_dows_range,
             check: """
               dows <@ ARRAY[0,1,2,3,4,5,6]::bigint[]
             """
           )

    create constraint(:professional_hours, :professional_hours_dow_range,
             check: """
               dow BETWEEN 0 AND 6
             """
           )
  end

  def down do
    drop_if_exists(constraint(:professional_hours, :professional_hours_dow_range))

    drop_if_exists(constraint(:package_schedules, :package_schedules_dows_range))

    drop_if_exists(constraint(:clinic_hours, :clinic_hours_dow_range))

    drop_if_exists(constraint(:availability_rules, :availability_rules_forma))

    drop_if_exists(index(:messages, [:provider_message_id], name: "messages_provider_id_index"))

    create index(:messages, [:provider_message_id], name: "messages_provider_id_index")
  end
end
