defmodule Api.Repo.Migrations.IndicesDeFkETrilhaDeletavel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:attendances_versions, "attendances_versions_version_source_id_fkey"))

    alter table(:attendances_versions) do
      modify(:version_source_id, :uuid)
    end

    create index(:attendances_versions, [:clinic_id, :version_source_id])

    drop(constraint(:appointments_versions, "appointments_versions_version_source_id_fkey"))

    alter table(:appointments_versions) do
      modify(:version_source_id, :uuid)
    end

    create index(:appointments_versions, [:clinic_id, :version_source_id])

    # Os dois `create index` acima são DERIVADOS: ao deixar de ser FK, o AshPostgres passa a
    # indexar `version_source_id` por conta própria (com `clinic_id` na frente, ADR-017). Só
    # que `20260719200000_agenda_constraint_and_rls.exs` já criara os mesmos dois índices à
    # mão, com outro nome — mesmas colunas, mesma ordem, mesmo método. Byte a byte iguais.
    #
    # Manter os dois é custo de escrita puro em duas tabelas que crescem a cada update de
    # agendamento. Fica o derivado, porque ele se mantém sozinho nos codegens futuros; sai o
    # escrito à mão, que o Ash não conhece e ninguém regeneraria.
    execute "DROP INDEX IF EXISTS appointments_versions_clinic_source_idx"
    execute "DROP INDEX IF EXISTS attendances_versions_clinic_source_idx"

    create index(:appointments, [:created_by_id])

    create index(:appointments, [:appointment_type_id])
  end

  def down do
    # Devolve os índices à mão que o `up` removeu, para que reverter esta migração deixe o
    # banco como `20260719200000` o entregou.
    execute """
    CREATE INDEX IF NOT EXISTS appointments_versions_clinic_source_idx
      ON appointments_versions (clinic_id, version_source_id)
    """

    execute """
    CREATE INDEX IF NOT EXISTS attendances_versions_clinic_source_idx
      ON attendances_versions (clinic_id, version_source_id)
    """

    drop_if_exists(index(:appointments, [:appointment_type_id]))

    drop_if_exists(index(:appointments, [:created_by_id]))

    drop_if_exists(index(:appointments_versions, [:clinic_id, :version_source_id]))

    alter table(:appointments_versions) do
      modify(
        :version_source_id,
        references(:appointments,
          column: :id,
          name: "appointments_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:attendances_versions, [:clinic_id, :version_source_id]))

    alter table(:attendances_versions) do
      modify(
        :version_source_id,
        references(:attendances,
          column: :id,
          name: "attendances_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end
end
