defmodule Api.Repo.Migrations.AvatarDoUsuario do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:avatar_key, :text)
      add(:avatar_origem, :text)
    end
  end

  def down do
    alter table(:users) do
      remove(:avatar_origem)
      remove(:avatar_key)
    end
  end
end
