defmodule Api.Repo.Migrations.AddPatients do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:patients, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:nome, :text, null: false)
      add(:nome_social, :text)
      add(:cpf, :text)
      add(:rg, :text)
      add(:genero, :text)
      add(:estado_civil, :text)
      add(:nascimento, :date)
      add(:responsavel, :text)
      add(:tel, :text)
      add(:email, :text)
      add(:cep, :text)
      add(:endereco, :text)
      add(:numero, :text)
      add(:complemento, :text)
      add(:bairro, :text)
      add(:cidade, :text)
      add(:uf, :text)
      add(:emergencia_nome, :text)
      add(:emergencia_parentesco, :text)
      add(:emergencia_tel, :text)
      add(:profissao, :text)
      add(:empresa, :text)
      add(:atend_tipo, :text, null: false, default: "particular")
      add(:medico, :text)
      add(:crm, :text)
      add(:como_conheceu, :text)
      add(:convenio, :text)
      add(:carteirinha, :text)
      add(:convenio_validade, :text)
      add(:prefs, {:array, :uuid}, default: [])
      add(:tags, {:array, :text}, default: [])
      add(:lgpd, :boolean, null: false, default: false)
      add(:comunicacao, :boolean, null: false, default: false)
      add(:cor_indice, :bigint, null: false, default: 1)
      add(:ativo, :boolean, null: false, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "patients_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create index(:patients, [:clinic_id])
  end

  def down do
    drop(constraint(:patients, "patients_clinic_id_fkey"))

    drop_if_exists(index(:patients, [:clinic_id]))

    drop(table(:patients))
  end
end
