defmodule Api.Repo.Migrations.S7EventosDeWebhookVistos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webhook_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:provider, :text, null: false)
      add(:digest, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:webhook_events, [:provider, :digest],
             name: "webhook_events_um_por_corpo_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:webhook_events, [:provider, :digest],
        name: "webhook_events_um_por_corpo_index"
      )
    )

    drop(table(:webhook_events))
  end
end
