defmodule Api.Repo.Migrations.A5OptOutVigenteUnico do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      index(:message_opt_outs, [:canal, :destino], name: "message_opt_outs_vigentes_index")
    )

    create unique_index(:message_opt_outs, [:canal, :destino, :clinic_id],
             name: "message_opt_outs_vigente_por_destino_index",
             nulls_distinct: false,
             where: "((revogado_em)::timestamp IS NULL)"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:message_opt_outs, [:canal, :destino, :clinic_id],
        name: "message_opt_outs_vigente_por_destino_index"
      )
    )

    create index(:message_opt_outs, [:canal, :destino],
             name: "message_opt_outs_vigentes_index",
             where: "(revogado_em)::timestamp IS NULL"
           )
  end
end
