defmodule Api.Repo.Migrations.AddAgenda do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:attendances_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:status, :text, null: false, default: "prevista")
      add(:clinic_id, :uuid, null: false)
      add(:appointment_id, :uuid, null: false)
      add(:patient_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:user_id, :uuid)
    end

    create table(:attendances, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:attendances_versions) do
      modify(
        :version_source_id,
        references(:attendances,
          column: :id,
          name: "attendances_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :user_id,
        references(:users,
          column: :id,
          name: "attendances_versions_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nothing,
          on_update: :update_all
        )
      )
    end

    alter table(:attendances) do
      add(:status, :text, null: false, default: "prevista")
      add(:falta_justificada, :boolean, null: false, default: false)
      add(:package_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "attendances_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(:appointment_id, :uuid, null: false)
      add(:patient_id, :uuid, null: false)
    end

    create index(:attendances, [:clinic_id, :package_id])

    create index(:attendances, [:clinic_id, :patient_id])

    create index(:attendances, [:clinic_id, :appointment_id])

    create unique_index(:attendances, [:clinic_id, :appointment_id, :patient_id],
             name: "attendances_one_per_patient_per_appt_index"
           )

    create table(:appointments_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:starts_at, :utc_datetime, null: false)
      add(:status, :text, null: false, default: "agendado")
      add(:clinic_id, :uuid, null: false)
      add(:professional_id, :uuid, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:user_id, :uuid)
    end

    create table(:appointments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:attendances) do
      modify(
        :appointment_id,
        references(:appointments,
          column: :id,
          name: "attendances_appointment_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :patient_id,
        references(:patients,
          column: :id,
          name: "attendances_patient_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter table(:appointments_versions) do
      modify(
        :version_source_id,
        references(:appointments,
          column: :id,
          name: "appointments_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :user_id,
        references(:users,
          column: :id,
          name: "appointments_versions_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nothing,
          on_update: :update_all
        )
      )
    end

    alter table(:appointments) do
      add(:starts_at, :utc_datetime, null: false)
      add(:ends_at, :utc_datetime, null: false)
      add(:status, :text, null: false, default: "agendado")
      add(:encaixe, :boolean, null: false, default: false)
      add(:obs, :text)
      add(:duration_minutos, :bigint)
      add(:cancel_reason, :text)
      add(:version, :bigint, null: false, default: 1)
      add(:package_id, :uuid)
      add(:pkg_hold, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "appointments_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :professional_id,
        references(:professionals,
          column: :id,
          name: "appointments_professional_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :appointment_type_id,
        references(:appointment_types,
          column: :id,
          name: "appointments_appointment_type_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :created_by_id,
        references(:users,
          column: :id,
          name: "appointments_created_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create index(:appointments, [:clinic_id, :package_id])

    create index(:appointments, [:clinic_id, :starts_at])

    create index(:appointments, [:clinic_id, :professional_id, :starts_at])
  end

  def down do
    drop(constraint(:appointments, "appointments_clinic_id_fkey"))

    drop(constraint(:appointments, "appointments_professional_id_fkey"))

    drop(constraint(:appointments, "appointments_appointment_type_id_fkey"))

    drop(constraint(:appointments, "appointments_created_by_id_fkey"))

    drop_if_exists(index(:appointments, [:clinic_id, :professional_id, :starts_at]))

    drop_if_exists(index(:appointments, [:clinic_id, :starts_at]))

    drop_if_exists(index(:appointments, [:clinic_id, :package_id]))

    alter table(:appointments) do
      remove(:created_by_id)
      remove(:appointment_type_id)
      remove(:professional_id)
      remove(:clinic_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:pkg_hold)
      remove(:package_id)
      remove(:version)
      remove(:cancel_reason)
      remove(:duration_minutos)
      remove(:obs)
      remove(:encaixe)
      remove(:status)
      remove(:ends_at)
      remove(:starts_at)
    end

    drop(constraint(:appointments_versions, "appointments_versions_version_source_id_fkey"))

    drop(constraint(:appointments_versions, "appointments_versions_user_id_fkey"))

    alter table(:appointments_versions) do
      modify(:user_id, :uuid)
      modify(:version_source_id, :uuid)
    end

    drop(constraint(:attendances, "attendances_appointment_id_fkey"))

    drop(constraint(:attendances, "attendances_patient_id_fkey"))

    alter table(:attendances) do
      modify(:patient_id, :uuid)
      modify(:appointment_id, :uuid)
    end

    drop(table(:appointments))

    drop(table(:appointments_versions))

    drop(constraint(:attendances, "attendances_clinic_id_fkey"))

    drop_if_exists(
      unique_index(:attendances, [:clinic_id, :appointment_id, :patient_id],
        name: "attendances_one_per_patient_per_appt_index"
      )
    )

    drop_if_exists(index(:attendances, [:clinic_id, :appointment_id]))

    drop_if_exists(index(:attendances, [:clinic_id, :patient_id]))

    drop_if_exists(index(:attendances, [:clinic_id, :package_id]))

    alter table(:attendances) do
      remove(:patient_id)
      remove(:appointment_id)
      remove(:clinic_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:package_id)
      remove(:falta_justificada)
      remove(:status)
    end

    drop(constraint(:attendances_versions, "attendances_versions_version_source_id_fkey"))

    drop(constraint(:attendances_versions, "attendances_versions_user_id_fkey"))

    alter table(:attendances_versions) do
      modify(:user_id, :uuid)
      modify(:version_source_id, :uuid)
    end

    drop(table(:attendances))

    drop(table(:attendances_versions))
  end
end
