defmodule Api.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(index(:audit_events, [:clinic_id, :at], name: "audit_events_feed_index"))

    # Os dois índices já existem quando a IndicesDasFacetas (à mão, CONCURRENTLY) rodou antes;
    # num banco zerado (test/CI) é esta migration que os cria. `if_not_exists` cobre os dois casos.
    create_if_not_exists(
      index(:audit_events, [:clinic_id, :resource, :at], name: "audit_events_resource_index")
    )

    create_if_not_exists(
      index(:audit_events, [:clinic_id, :action, :at], name: "audit_events_action_index")
    )

    create index(:audit_events, [:clinic_id, :at, :id], name: "audit_events_feed_index")
  end

  def down do
    drop_if_exists(index(:audit_events, [:clinic_id, :at, :id], name: "audit_events_feed_index"))

    drop_if_exists(
      index(:audit_events, [:clinic_id, :action, :at], name: "audit_events_action_index")
    )

    drop_if_exists(
      index(:audit_events, [:clinic_id, :resource, :at], name: "audit_events_resource_index")
    )

    create index(:audit_events, [:clinic_id, :at], name: "audit_events_feed_index")
  end
end
