defmodule Api.Repo.Migrations.AddClinicHoursAndExceptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:schedule_exceptions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:data, :date, null: false)
      add(:nome, :text)
      add(:tipo, :text, null: false)
      add(:periods, {:array, {:array, :text}}, null: false, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "schedule_exceptions_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :professional_id,
        references(:professionals,
          column: :id,
          name: "schedule_exceptions_professional_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    create index(:schedule_exceptions, [:clinic_id])

    create unique_index(:schedule_exceptions, [:clinic_id, :data, :professional_id],
             name: "schedule_exceptions_one_per_data_prof_index",
             nulls_distinct: false
           )

    create table(:clinic_hours, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:dow, :bigint, null: false)
      add(:periods, {:array, {:array, :text}}, null: false, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "clinic_hours_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create index(:clinic_hours, [:clinic_id])

    create unique_index(:clinic_hours, [:clinic_id, :dow], name: "clinic_hours_one_per_dow_index")
  end

  def down do
    drop(constraint(:clinic_hours, "clinic_hours_clinic_id_fkey"))

    drop_if_exists(
      unique_index(:clinic_hours, [:clinic_id, :dow], name: "clinic_hours_one_per_dow_index")
    )

    drop_if_exists(index(:clinic_hours, [:clinic_id]))

    drop(table(:clinic_hours))

    drop(constraint(:schedule_exceptions, "schedule_exceptions_clinic_id_fkey"))

    drop(constraint(:schedule_exceptions, "schedule_exceptions_professional_id_fkey"))

    drop_if_exists(
      unique_index(:schedule_exceptions, [:clinic_id, :data, :professional_id],
        name: "schedule_exceptions_one_per_data_prof_index"
      )
    )

    drop_if_exists(index(:schedule_exceptions, [:clinic_id]))

    drop(table(:schedule_exceptions))
  end
end
