defmodule Api.Repo.Migrations.AddPatientsPaginationIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(index(:patients, [:clinic_id]))

    create index(:patients, [:clinic_id, :inserted_at])
  end

  def down do
    drop_if_exists(index(:patients, [:clinic_id, :inserted_at]))

    create index(:patients, [:clinic_id])
  end
end
