defmodule Api.Repo.Migrations.PresencaSegurada do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:attendances) do
      add(:pkg_hold, :boolean, null: false, default: false)
    end
  end

  def down do
    alter table(:attendances) do
      remove(:pkg_hold)
    end
  end
end
