defmodule Api.Repo.Migrations.IndiceDeSubjectDosTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  ## Nota de revisão (doc 92, P1-4)

  O índice serve `revoke_all_stored_for_subject` — o "sair de todas as sessões". Medido em 200.000
  tokens: `Seq Scan` 2.131 buffers / 13,1 ms → `Bitmap Index Scan` 42 buffers / 0,118 ms.

  `CONCURRENTLY` (e as duas anotações que ele exige) porque `tokens` recebe INSERT em todo login e
  esta migration roda no `release_command` do deploy — `.claude/rules/migrations.md` §2. O `down`
  foi ajustado à mão para dropar do mesmo jeito, pelo mesmo motivo; o gerador emite o `drop` comum.
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:tokens, [:subject], concurrently: true)
  end

  def down do
    drop_if_exists(index(:tokens, [:subject], concurrently: true))
  end
end
