defmodule Api.Repo.Migrations.AceiteDosTermos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:termos_aceitos_em, :utc_datetime)
      add(:termos_versao, :text)
    end
  end

  def down do
    alter table(:users) do
      remove(:termos_versao)
      remove(:termos_aceitos_em)
    end
  end
end
