defmodule Api.Repo.Migrations.ContatoEEnderecoDaClinica do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clinics) do
      add(:telefone, :text)
      add(:cep, :text)
      add(:numero, :text)
      add(:complemento, :text)
      add(:bairro, :text)
      add(:cidade, :text)
      add(:uf, :text)
      add(:msg_whatsapp_ativo, :boolean, null: false, default: false)
    end
  end

  def down do
    alter table(:clinics) do
      remove(:msg_whatsapp_ativo)
      remove(:uf)
      remove(:cidade)
      remove(:bairro)
      remove(:complemento)
      remove(:numero)
      remove(:cep)
      remove(:telefone)
    end
  end
end
