defmodule Api.Repo.Migrations.AddAppointmentsProfessionalIdIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:appointments, [:professional_id])
  end

  def down do
    drop_if_exists(index(:appointments, [:professional_id]))
  end
end
