defmodule Api.Repo.Migrations.UnicidadeDaGradeDoPacote do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  ## Duas notas para quem revisar (doc 92, P1-2)

  **Sem `CONCURRENTLY`, de propósito.** A regra de `.claude/rules/migrations.md` §2 é sobre tabela
  **com dado** — `CONCURRENTLY` faz duas varreduras e é mais lento em tabela pequena. Aqui são 3
  linhas / 64 kB (uma por pacote), e a janela de `ShareLock` é de milissegundos.

  **Falha segura se houver duplicata.** O `CREATE UNIQUE INDEX` recusa se alguma clínica já tiver
  duas grades para o mesmo pacote — a migration aborta e nada é corrompido. Antes de aplicar em
  produção, confira:

      SELECT clinic_id, package_id, count(*)
        FROM package_schedules GROUP BY 1, 2 HAVING count(*) > 1;
  """

  use Ecto.Migration

  def up do
    drop_if_exists(index(:package_schedules, [:clinic_id, :package_id]))

    create unique_index(:package_schedules, [:clinic_id, :package_id],
             name: "package_schedules_one_schedule_per_package_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:package_schedules, [:clinic_id, :package_id],
        name: "package_schedules_one_schedule_per_package_index"
      )
    )

    create index(:package_schedules, [:clinic_id, :package_id])
  end
end
