defmodule Api.Repo.Migrations.AddAppointmentsDurationCheck do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:appointments, :appointments_ends_after_starts,
             check: """
               ends_at > starts_at
             """
           )
  end

  def down do
    drop_if_exists(constraint(:appointments, :appointments_ends_after_starts))
  end
end
