defmodule Api.Repo.Migrations.NumeroDeWhatsappPorClinica do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clinics) do
      add(:zernio_account_id, :text)
    end
  end

  def down do
    alter table(:clinics) do
      remove(:zernio_account_id)
    end
  end
end
