defmodule Api.Repo.Migrations.OrigemNaFilaDeEspera do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add(:veio_da_fila, :boolean, null: false, default: false)
      add(:dias_na_fila, :bigint)
    end
  end

  def down do
    alter table(:appointments) do
      remove(:dias_na_fila)
      remove(:veio_da_fila)
    end
  end
end
