defmodule Api.Repo.Migrations.TrilhaDeEventos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:resource, :text, null: false)
      add(:action_type, :text, null: false)
      add(:action, :text, null: false)
      add(:record_id, :uuid)
      add(:user_id, :uuid)
      add(:label, :text)
      add(:user_label, :text)
      add(:at, :utc_datetime_usec, null: false)
      add(:diff, {:array, :map}, null: false, default: [])
      add(:meta, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "audit_events_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create index(:audit_events, [:clinic_id, :user_id, :at], name: "audit_events_author_index")

    create index(:audit_events, [:clinic_id, :resource, :record_id, :at],
             name: "audit_events_record_index"
           )

    create index(:audit_events, [:clinic_id, :at], name: "audit_events_feed_index")
  end

  def down do
    drop(constraint(:audit_events, "audit_events_clinic_id_fkey"))

    drop_if_exists(index(:audit_events, [:clinic_id, :at], name: "audit_events_feed_index"))

    drop_if_exists(
      index(:audit_events, [:clinic_id, :resource, :record_id, :at],
        name: "audit_events_record_index"
      )
    )

    drop_if_exists(
      index(:audit_events, [:clinic_id, :user_id, :at], name: "audit_events_author_index")
    )

    drop(table(:audit_events))
  end
end
