defmodule Api.Repo.Migrations.AnexosDePaciente do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:attachments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:nome, :text, null: false)
      add(:chave, :text, null: false)
      add(:content_type, :text, null: false)
      add(:bytes, :bigint, null: false)
      add(:status, :text, null: false, default: "pendente")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "attachments_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :patient_id,
        references(:patients,
          column: :id,
          name: "attachments_patient_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :uploaded_by_id,
        references(:users,
          column: :id,
          name: "attachments_uploaded_by_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nilify_all
        )
      )
    end

    create index(:attachments, [:uploaded_by_id])

    create index(:attachments, [:patient_id])

    create index(:attachments, [:clinic_id, :patient_id, :inserted_at])

    create table(:attachment_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:acao, :text, null: false)
      add(:attachment_id, :uuid, null: false)
      add(:patient_id, :uuid, null: false)
      add(:user_id, :uuid)
      add(:nome, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "attachment_events_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create index(:attachment_events, [:clinic_id, :attachment_id, :inserted_at])
  end

  def down do
    drop(constraint(:attachment_events, "attachment_events_clinic_id_fkey"))

    drop_if_exists(index(:attachment_events, [:clinic_id, :attachment_id, :inserted_at]))

    drop(table(:attachment_events))

    drop(constraint(:attachments, "attachments_clinic_id_fkey"))

    drop(constraint(:attachments, "attachments_patient_id_fkey"))

    drop(constraint(:attachments, "attachments_uploaded_by_id_fkey"))

    drop_if_exists(index(:attachments, [:clinic_id, :patient_id, :inserted_at]))

    drop_if_exists(index(:attachments, [:patient_id]))

    drop_if_exists(index(:attachments, [:uploaded_by_id]))

    drop(table(:attachments))
  end
end
