defmodule Api.Repo.Migrations.SemanticaOnDeleteH64 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  **Editada à mão em dois pontos** (H64, Onda 5), e o porquê está em cada um:

  1. o par `drop_if_exists(index …)` / `create index(…)` sobre
     `attendances_clinic_id_package_id_index` foi **removido**. Ele é artefato da transição: o
     índice deixou de ser declarado em `custom_indexes` e passou a vir do `belongs_to :package`,
     com o **mesmo nome e as mesmas colunas**. Executá-lo derrubaria e reconstruiria um índice
     idêntico numa tabela com 10.219 linhas — e um `CREATE INDEX` comum toma `ShareLock`, que fila
     todo `INSERT`/`UPDATE` da tabela enquanto constrói (`.claude/rules/migrations.md`);
  2. o `on_delete` de `attendances.package_id` era `NULL` antes desta migration — a coluna existia
     **sem FK nenhuma**. Por isso ela é `modify` de uma coluna solta para uma referência, e o
     `down` a devolve a `:uuid` puro.
  """

  use Ecto.Migration

  def up do
    drop(constraint(:attendances_versions, "attendances_versions_user_id_fkey"))

    alter table(:attendances_versions) do
      modify(
        :user_id,
        references(:users,
          column: :id,
          name: "attendances_versions_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nilify_all,
          on_update: :update_all
        )
      )
    end

    alter table(:attendances) do
      modify(
        :package_id,
        references(:packages,
          column: :id,
          name: "attendances_package_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nilify_all
        )
      )
    end

    drop(constraint(:appointments_versions, "appointments_versions_user_id_fkey"))

    alter table(:appointments_versions) do
      modify(
        :user_id,
        references(:users,
          column: :id,
          name: "appointments_versions_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nilify_all,
          on_update: :update_all
        )
      )
    end

    drop(constraint(:appointments, "appointments_created_by_id_fkey"))

    alter table(:appointments) do
      modify(
        :created_by_id,
        references(:users,
          column: :id,
          name: "appointments_created_by_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nilify_all
        )
      )
    end
  end

  def down do
    drop(constraint(:appointments, "appointments_created_by_id_fkey"))

    alter table(:appointments) do
      modify(
        :created_by_id,
        references(:users,
          column: :id,
          name: "appointments_created_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:appointments_versions, "appointments_versions_user_id_fkey"))

    alter table(:appointments_versions) do
      modify(
        :user_id,
        references(:users,
          column: :id,
          name: "appointments_versions_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nothing,
          on_update: :update_all
        )
      )
    end

    drop(constraint(:attendances, "attendances_package_id_fkey"))

    alter table(:attendances) do
      modify(:package_id, :uuid)
    end

    drop(constraint(:attendances_versions, "attendances_versions_user_id_fkey"))

    alter table(:attendances_versions) do
      modify(
        :user_id,
        references(:users,
          column: :id,
          name: "attendances_versions_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nothing,
          on_update: :update_all
        )
      )
    end
  end
end
