defmodule Api.Repo.Migrations.AddWaitlist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:waitlist_entries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:prio, :text, null: false, default: "normal")
      add(:janela, :text, null: false, default: "qualquer")
      add(:obs, :text)
      add(:professional_ids, {:array, :uuid}, null: false, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "waitlist_entries_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :patient_id,
        references(:patients,
          column: :id,
          name: "waitlist_entries_patient_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create index(:waitlist_entries, [:patient_id])

    create unique_index(:waitlist_entries, [:clinic_id, :patient_id],
             name: "waitlist_entries_one_entry_per_patient_index"
           )

    create table(:slot_holds, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:starts_at, :utc_datetime, null: false)
      add(:ends_at, :utc_datetime, null: false)
      add(:expires_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "slot_holds_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :professional_id,
        references(:professionals,
          column: :id,
          name: "slot_holds_professional_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :waitlist_entry_id,
        references(:waitlist_entries,
          column: :id,
          name: "slot_holds_waitlist_entry_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :held_by_id,
        references(:users,
          column: :id,
          name: "slot_holds_held_by_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create index(:slot_holds, [:held_by_id])

    create index(:slot_holds, [:waitlist_entry_id])

    create index(:slot_holds, [:clinic_id, :professional_id, :starts_at])

    create table(:availability_rules, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:tipo, :text, null: false)
      add(:dows, {:array, :bigint}, null: false, default: [])
      add(:data, :date)
      add(:periodos, {:array, {:array, :text}}, null: false, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "availability_rules_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :waitlist_entry_id,
        references(:waitlist_entries,
          column: :id,
          name: "availability_rules_waitlist_entry_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create index(:availability_rules, [:waitlist_entry_id])
  end

  def down do
    drop(constraint(:availability_rules, "availability_rules_clinic_id_fkey"))

    drop(constraint(:availability_rules, "availability_rules_waitlist_entry_id_fkey"))

    drop_if_exists(index(:availability_rules, [:waitlist_entry_id]))

    drop(table(:availability_rules))

    drop(constraint(:slot_holds, "slot_holds_clinic_id_fkey"))

    drop(constraint(:slot_holds, "slot_holds_professional_id_fkey"))

    drop(constraint(:slot_holds, "slot_holds_waitlist_entry_id_fkey"))

    drop(constraint(:slot_holds, "slot_holds_held_by_id_fkey"))

    drop_if_exists(index(:slot_holds, [:clinic_id, :professional_id, :starts_at]))

    drop_if_exists(index(:slot_holds, [:waitlist_entry_id]))

    drop_if_exists(index(:slot_holds, [:held_by_id]))

    drop(table(:slot_holds))

    drop(constraint(:waitlist_entries, "waitlist_entries_clinic_id_fkey"))

    drop(constraint(:waitlist_entries, "waitlist_entries_patient_id_fkey"))

    drop_if_exists(
      unique_index(:waitlist_entries, [:clinic_id, :patient_id],
        name: "waitlist_entries_one_entry_per_patient_index"
      )
    )

    drop_if_exists(index(:waitlist_entries, [:patient_id]))

    drop(table(:waitlist_entries))
  end
end
