defmodule Api.Repo.Migrations.AddAppointmentTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:appointment_types, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:nome, :text, null: false)
      add(:duracao_minutos, :bigint, null: false)
      add(:cor, :text, null: false)
      add(:icon, :text, null: false)
      add(:grupo, :boolean, null: false, default: false)
      add(:capacidade, :bigint)
      add(:ativo, :boolean, null: false, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "appointment_types_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create unique_index(:appointment_types, [:clinic_id, :nome],
             name: "appointment_types_unique_nome_index"
           )
  end

  def down do
    drop(constraint(:appointment_types, "appointment_types_clinic_id_fkey"))

    drop_if_exists(
      unique_index(:appointment_types, [:clinic_id, :nome],
        name: "appointment_types_unique_nome_index"
      )
    )

    drop(table(:appointment_types))
  end
end
