defmodule Api.Repo.Migrations.NotificacoesIndiceNaoLidasComCast do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      index(:notifications, [:clinic_id, :recipient_id, :inserted_at],
        name: "notifications_unread_index"
      )
    )

    create index(:notifications, [:clinic_id, :recipient_id, :inserted_at],
             name: "notifications_unread_index",
             where: "(read_at)::timestamp IS NULL"
           )
  end

  def down do
    drop_if_exists(
      index(:notifications, [:clinic_id, :recipient_id, :inserted_at],
        name: "notifications_unread_index"
      )
    )

    create index(:notifications, [:clinic_id, :recipient_id, :inserted_at],
             name: "notifications_unread_index",
             where: "read_at IS NULL"
           )
  end
end
