defmodule Api.Repo.Migrations.AddNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:kind, :text, null: false)
      add(:title, :text, null: false)
      add(:body, :text, null: false)
      add(:data, :map, null: false, default: %{})
      add(:read_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "notifications_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :recipient_id,
        references(:users,
          column: :id,
          name: "notifications_recipient_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create index(:notifications, [:recipient_id])

    create index(:notifications, [:clinic_id, :recipient_id, :read_at])
  end

  def down do
    drop(constraint(:notifications, "notifications_clinic_id_fkey"))

    drop(constraint(:notifications, "notifications_recipient_id_fkey"))

    drop_if_exists(index(:notifications, [:clinic_id, :recipient_id, :read_at]))

    drop_if_exists(index(:notifications, [:recipient_id]))

    drop(table(:notifications))
  end
end
