defmodule Api.Repo.Migrations.DuracaoMaximaNoBanco do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:appointments, :appointments_duration_within_cap,
             check: """
               ends_at <= starts_at + interval '480 minutes'
             """
           )
  end

  def down do
    drop_if_exists(constraint(:appointments, :appointments_duration_within_cap))
  end
end
