defmodule Api.Repo.Migrations.RemoveAppointmentPackageId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  **Destrutiva de propósito, e o dado foi conferido antes** (Onda 5, docs/46 §6c):
  `appointments.package_id` estava em **0 de 10.212 linhas**. Ela era "gancho da Fatia 3", e a
  A2 (doc 41 etapa 2) decidiu que pacote é por **participante** (D11: não existe pacote de
  turma) — o vínculo nasce na `Attendance` e nunca mais chegou aqui. Ficava custando escrita:
  o índice `appointments_clinic_id_package_id_index` era mantido a cada `INSERT`/`UPDATE` de uma
  tabela quente para uma coluna sempre nula.

  `remove/1` de coluna é operação de catálogo (não reescreve a tabela), e o `drop index` toma
  `ACCESS EXCLUSIVE` por instantes — diferente do `CREATE INDEX`, não há construção a esperar.
  O `down` é honesto: recria a coluna e o índice **vazios**. Não há dado a restaurar porque não
  havia dado.
  """

  use Ecto.Migration

  def up do
    drop_if_exists(index(:appointments, [:clinic_id, :package_id]))

    alter table(:appointments) do
      remove(:package_id)
    end
  end

  def down do
    alter table(:appointments) do
      add(:package_id, :uuid)
    end

    create index(:appointments, [:clinic_id, :package_id])
  end
end
