defmodule Api.Repo.Migrations.ConsentimentoDeComunicacaoPadrao do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:patients) do
      modify(:comunicacao, :boolean, default: true)
    end
  end

  def down do
    alter table(:patients) do
      modify(:comunicacao, :boolean, default: false)
    end
  end
end
