defmodule Api.Repo.Migrations.RemoveClinicFaltaConsomePadrao do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clinics) do
      remove(:falta_consome_padrao)
    end
  end

  def down do
    alter table(:clinics) do
      add(:falta_consome_padrao, :boolean, null: false, default: false)
    end
  end
end
