defmodule Api.Repo.Migrations.FkDoProfissionalNoMembership do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  ## Nota de revisão (doc 92, P1-3(b))

  `memberships.professional_id` era um `attribute :uuid` sem FK — o "UUID mole". Virou `belongs_to`
  para ganhar esta constraint. A FK é **global**: garante que o profissional existe, **não** que é
  da mesma clínica. A metade cross-tenant continua sendo trabalho da
  `Validations.ProfessionalInClinic`, presente nas três portas de escrita desde a Onda 1.

  **O índice não é enfeite.** `ON DELETE SET NULL` faz o `DELETE` do profissional **escrever** em
  toda linha correspondente, e a checagem emite `WHERE professional_id = $1` — sem `clinic_id`,
  porque o Postgres não tem noção de tenant. O único índice que havia com essa coluna é o da
  identity `unique_professional_link`, `(clinic_id, professional_id)`, onde ela **não lidera**. É a
  mesma lição da migration `20260726210945_indice_fk_package_da_presenca`.

  **Sem `CONCURRENTLY`**: `memberships` tem uma linha por pessoa por clínica — dezenas, não
  milhares. O `ADD FOREIGN KEY` toma `AccessExclusiveLock` nas duas tabelas enquanto valida; nesse
  volume é instantâneo. Se um dia não for, o padrão é `NOT VALID` + `VALIDATE CONSTRAINT`.

  **Antes de aplicar em produção**, confira que não há órfão — a migration aborta se houver:

      SELECT count(*) FROM memberships m
       WHERE m.professional_id IS NOT NULL
         AND NOT EXISTS (SELECT 1 FROM professionals p WHERE p.id = m.professional_id);

  No dev, em 2026-08-04, deu **0**.
  """

  use Ecto.Migration

  # O gerador emite `alter table … modify(:professional_id, references(...))`, e o Postgres recusa:
  #
  #     ERROR 0A000 (feature_not_supported)
  #     cannot alter type of a column used by a view or rule
  #
  # A view é `metrics_memberships` (doc 73). O `modify` do Ecto **redeclara o tipo** da coluna, e
  # isso basta para a recusa — mesmo o tipo sendo o mesmo (`uuid` → `uuid`) e a mudança real sendo
  # só a constraint. Escrito à mão, o `ADD CONSTRAINT` não toca no tipo e passa sem mexer na view.
  def up do
    execute """
    ALTER TABLE memberships
      ADD CONSTRAINT memberships_professional_id_fkey
      FOREIGN KEY (professional_id) REFERENCES professionals (id) ON DELETE SET NULL
    """

    create index(:memberships, [:professional_id])
  end

  def down do
    drop_if_exists(index(:memberships, [:professional_id]))

    execute "ALTER TABLE memberships DROP CONSTRAINT IF EXISTS memberships_professional_id_fkey"
  end
end
