defmodule Api.Repo.Migrations.ComunicacaoComOPaciente do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:canal, :text, null: false)
      add(:kind, :text, null: false)
      add(:template, :text, null: false)
      add(:vars, :map, null: false, default: %{})
      add(:destino, :text, null: false)
      add(:status, :text, null: false, default: "pendente")
      add(:provider, :text)
      add(:provider_message_id, :text)
      add(:enfileirado_em, :utc_datetime)
      add(:enviado_em, :utc_datetime)
      add(:entregue_em, :utc_datetime)
      add(:lido_em, :utc_datetime)
      add(:falhou_em, :utc_datetime)
      add(:erro, :text)
      add(:respondido_em, :utc_datetime)
      add(:resposta, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "messages_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :attendance_id,
        references(:attendances,
          column: :id,
          name: "messages_attendance_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :appointment_id,
        references(:appointments,
          column: :id,
          name: "messages_appointment_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :patient_id,
        references(:patients,
          column: :id,
          name: "messages_patient_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :disparado_por_id,
        references(:users,
          column: :id,
          name: "messages_disparado_por_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nilify_all
        )
      )
    end

    create index(:messages, [:disparado_por_id])

    create index(:messages, [:attendance_id])

    create index(:messages, [:provider_message_id], name: "messages_provider_id_index")

    create index(:messages, [:clinic_id, :appointment_id, :inserted_at],
             name: "messages_appointment_index"
           )

    create table(:message_opt_outs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:canal, :text, null: false)
      add(:destino, :text, null: false)
      add(:origem, :text, null: false)
      add(:motivo, :text)
      add(:revogado_em, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "message_opt_outs_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      add(
        :revogado_por_id,
        references(:users,
          column: :id,
          name: "message_opt_outs_revogado_por_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nilify_all
        )
      )
    end

    create index(:message_opt_outs, [:revogado_por_id])

    create index(:message_opt_outs, [:clinic_id])

    create index(:message_opt_outs, [:canal, :destino],
             name: "message_opt_outs_vigentes_index",
             where: "(revogado_em)::timestamp IS NULL"
           )

    alter table(:clinics) do
      add(:msg_confirmacao_auto, :boolean, null: false, default: true)
      add(:msg_lembrete_horas, :bigint)
      add(:msg_silencio_inicio, :bigint, default: 21)
      add(:msg_silencio_fim, :bigint, default: 8)
    end
  end

  def down do
    alter table(:clinics) do
      remove(:msg_silencio_fim)
      remove(:msg_silencio_inicio)
      remove(:msg_lembrete_horas)
      remove(:msg_confirmacao_auto)
    end

    drop(constraint(:message_opt_outs, "message_opt_outs_clinic_id_fkey"))

    drop(constraint(:message_opt_outs, "message_opt_outs_revogado_por_id_fkey"))

    drop_if_exists(
      index(:message_opt_outs, [:canal, :destino], name: "message_opt_outs_vigentes_index")
    )

    drop_if_exists(index(:message_opt_outs, [:clinic_id]))

    drop_if_exists(index(:message_opt_outs, [:revogado_por_id]))

    drop(table(:message_opt_outs))

    drop(constraint(:messages, "messages_clinic_id_fkey"))

    drop(constraint(:messages, "messages_attendance_id_fkey"))

    drop(constraint(:messages, "messages_appointment_id_fkey"))

    drop(constraint(:messages, "messages_patient_id_fkey"))

    drop(constraint(:messages, "messages_disparado_por_id_fkey"))

    drop_if_exists(
      index(:messages, [:clinic_id, :appointment_id, :inserted_at],
        name: "messages_appointment_index"
      )
    )

    drop_if_exists(index(:messages, [:provider_message_id], name: "messages_provider_id_index"))

    drop_if_exists(index(:messages, [:attendance_id]))

    drop_if_exists(index(:messages, [:disparado_por_id]))

    drop(table(:messages))
  end
end
