defmodule Api.Repo.Migrations.AddAppointmentExcludedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add(:excluded_at, :utc_datetime)
    end
  end

  def down do
    alter table(:appointments) do
      remove(:excluded_at)
    end
  end
end
