defmodule Api.Repo.Migrations.SchedulingIndexTuning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # bate-volta F3: dropar os índices standalone de `clinic_id` — redundantes com as
    # identidades únicas que já lideram por `clinic_id`.
    drop_if_exists(index(:schedule_exceptions, [:clinic_id]))
    drop_if_exists(index(:clinic_hours, [:clinic_id]))

    # bate-volta F1: índice de apoio à FK `professional_id` (leading, sem o `clinic_id` que o
    # Ash prefixaria) — o cascade `ON DELETE` faz `WHERE professional_id = $1`, e sem isto vira
    # seq scan quando a fatia de Profissionais (doc 22 §5) passar a deletar profissionais.
    # Escrito à mão: o gerador do Ash prefixaria o tenant e o índice não serviria o lookup.
    create index(:schedule_exceptions, [:professional_id])
  end

  def down do
    drop_if_exists(index(:schedule_exceptions, [:professional_id]))
    create index(:clinic_hours, [:clinic_id])
    create index(:schedule_exceptions, [:clinic_id])
  end
end
