defmodule Api.Repo.Migrations.DescarteDeMensagemNaFila do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add(:descartada_em, :utc_datetime)
      add(:descarte_motivo, :text)
    end
  end

  def down do
    alter table(:messages) do
      remove(:descarte_motivo)
      remove(:descartada_em)
    end
  end
end
