defmodule Api.Repo.Migrations.IndicesDeCascadeDasMensagens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:messages, [:patient_id])

    create index(:messages, [:appointment_id])
  end

  def down do
    drop_if_exists(index(:messages, [:appointment_id]))

    drop_if_exists(index(:messages, [:patient_id]))
  end
end
