defmodule Api.Repo.Migrations.AddClinicCnpjEndereco do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clinics) do
      add(:cnpj, :text)
      add(:endereco, :text)
    end
  end

  def down do
    alter table(:clinics) do
      remove(:endereco)
      remove(:cnpj)
    end
  end
end
