defmodule Api.Repo.Migrations.AddProfessionalsFullAndProfessionalHours do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:professionals) do
      add(:nome_exibicao, :text)
      add(:nascimento, :date)
      add(:cpf, :text)
      add(:rg, :text)
      add(:estado_civil, :text)
      add(:tel, :text)
      add(:email, :text)
      add(:cep, :text)
      add(:endereco, :text)
      add(:numero, :text)
      add(:complemento, :text)
      add(:bairro, :text)
      add(:cidade, :text)
      add(:uf, :text)
      add(:emergencia_nome, :text)
      add(:emergencia_tel, :text)
      add(:profissao, :text)
      add(:crefito, :text)
      add(:registro_uf, :text)
      add(:ano_conclusao, :text)
      add(:especialidades, {:array, :text}, default: [])
      add(:sub, :text)
      add(:vinculo, :text)
      add(:razao_social, :text)
      add(:cnpj, :text)
      add(:banco, :text)
      add(:agencia, :text)
      add(:conta, :text)
      add(:conta_tipo, :text)
      add(:pix, :text)
      add(:cor_indice, :bigint, null: false, default: 1)
      add(:segue_horario_clinica, :boolean, null: false, default: true)
      add(:ativo, :boolean, null: false, default: true)
    end

    create table(:professional_hours, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:dow, :bigint, null: false)
      add(:modo, :text, null: false)
      add(:periods, {:array, {:array, :text}}, null: false, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "professional_hours_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(
        :professional_id,
        references(:professionals,
          column: :id,
          name: "professional_hours_professional_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create unique_index(:professional_hours, [:clinic_id, :professional_id, :dow],
             name: "professional_hours_one_per_prof_dow_index"
           )
  end

  def down do
    drop(constraint(:professional_hours, "professional_hours_clinic_id_fkey"))

    drop(constraint(:professional_hours, "professional_hours_professional_id_fkey"))

    drop_if_exists(
      unique_index(:professional_hours, [:clinic_id, :professional_id, :dow],
        name: "professional_hours_one_per_prof_dow_index"
      )
    )

    drop(table(:professional_hours))

    alter table(:professionals) do
      remove(:ativo)
      remove(:segue_horario_clinica)
      remove(:cor_indice)
      remove(:pix)
      remove(:conta_tipo)
      remove(:conta)
      remove(:agencia)
      remove(:banco)
      remove(:cnpj)
      remove(:razao_social)
      remove(:vinculo)
      remove(:sub)
      remove(:especialidades)
      remove(:ano_conclusao)
      remove(:registro_uf)
      remove(:crefito)
      remove(:profissao)
      remove(:emergencia_tel)
      remove(:emergencia_nome)
      remove(:uf)
      remove(:cidade)
      remove(:bairro)
      remove(:complemento)
      remove(:numero)
      remove(:endereco)
      remove(:cep)
      remove(:email)
      remove(:tel)
      remove(:estado_civil)
      remove(:rg)
      remove(:cpf)
      remove(:nascimento)
      remove(:nome_exibicao)
    end
  end
end
