defmodule Api.Repo.Migrations.MotivoEmFaltaERemarcacao do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:attendances) do
      add(:motivo, :text)
    end

    alter table(:appointments) do
      add(:reschedule_reason, :text)
    end
  end

  def down do
    alter table(:appointments) do
      remove(:reschedule_reason)
    end

    alter table(:attendances) do
      remove(:motivo)
    end
  end
end
