defmodule Api.Repo.Migrations.AddAvailabilityRuleClinicIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:availability_rules, [:clinic_id])
  end

  def down do
    drop_if_exists(index(:availability_rules, [:clinic_id]))
  end
end
